---
- name: Install docker with script
  shell: curl -fsSL https://get.docker.com -o get-docker.sh && sudo sh ./get-docker.sh

- name: start and enable docker service
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Install docker-compose
  shell: sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && sudo chmod +x /usr/local/bin/docker-compose



